auto: true

markdown: rdiscount
pygments: true
paginate: 8
permalink: /:title

title: Huawei-OpenStack-Team
url: http://openstack-huawei.github.io/
feed: /atom.xml
author_info: <a href="http://openstack-huawei.github.io/">Huawei OpenStack Team</a>
